name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
      
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci
      
      - name: Build Angular app with prerendering
        working-directory: ./frontend
        run: |
          npm run build -- --configuration=production
          
          # Create deployment folder
          mkdir -p dist/deploy
          
          # Copy all prerendered files
          cp -r dist/iwa-app/browser/* dist/deploy/
          
          # Ensure index.html exists (rename if needed)
          [ -f "dist/deploy/index.csr.html" ] && mv dist/deploy/index.csr.html dist/deploy/index.html
          
          echo "Prerendered routes detected:"
          cat dist/iwa-app/prerendered-routes.json

      - name: Generate Azure routes configuration
        working-directory: ./frontend
        run: |
          # Create staticwebapp.config.json with all prerendered routes
          cat > dist/deploy/staticwebapp.config.json << 'EOL'
          {
            "routes": [
              {
                "route": "/",
                "serve": "/index.html",
                "statusCode": 200
              },
              {
                "route": "/Home",
                "serve": "/Home/index.html",
                "statusCode": 200
              },
              {
                "route": "/about",
                "serve": "/about/index.html",
                "statusCode": 200
              },
              {
                "route": "/blog",
                "serve": "/blog/index.html",
                "statusCode": 200
              },
              {
                "route": "/contact",
                "serve": "/contact/index.html",
                "statusCode": 200
              },
              {
                "route": "/news",
                "serve": "/news/index.html",
                "statusCode": 200
              },
              {
                "route": "/news-details",
                "serve": "/news-details/index.html",
                "statusCode": 200
              },
              {
                "route": "/*",
                "serve": "/index.html",
                "statusCode": 200
              }
            ],
            "navigationFallback": {
              "rewrite": "/index.html",
              "exclude": ["/assets/*", "/*.css", "/*.js"]
            },
            "responseOverrides": {
              "404": {
                "rewrite": "/index.html"
              }
            }
          }
          EOL
          
          echo "Azure Static Web Apps configuration:"
          cat dist/deploy/staticwebapp.config.json

      - name: Deploy to Azure
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_SEA_08385421E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "frontend/dist/deploy"
          output_location: ""
          routes_location: "frontend/dist/deploy/staticwebapp.config.json"
          skip_app_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_SEA_08385421E }}
          action: "close"
