name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
      
      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci
      
      - name: Build Angular app
        working-directory: ./frontend
        run: |
          # Build the application
          npm run build -- --configuration=production
          
          # Debug: Show directory structure
          echo "Build output structure:"
          find dist -type f
          
          # Prepare deployment folder
          mkdir -p dist/deploy
          
          # Copy all browser files to deploy folder
          if [ -d "dist/iwa-app/browser" ]; then
            cp -r dist/iwa-app/browser/* dist/deploy/
          else
            cp -r dist/iwa-app/* dist/deploy/
          fi
          
          # Ensure all HTML files are accessible
          find dist/deploy -name "*.html" -exec chmod 644 {} \;
          
          echo "Final deployment structure:"
          find dist/deploy -type f

      - name: Configure routes for multi-page app
        working-directory: ./frontend
        run: |
          # Create routes.json for Azure Static Web Apps
          cat > dist/deploy/routes.json << 'EOL'
          {
            "routes": [
              {
                "route": "/Home",
                "serve": "/Home/index.html",
                "statusCode": 200
              },
              {
                "route": "/About",
                "serve": "/About/index.html",
                "statusCode": 200
              },
              {
                "route": "/*",
                "serve": "/index.html",
                "statusCode": 200
              }
            ],
            "navigationFallback": {
              "rewrite": "/index.html",
              "exclude": ["/assets/*"]
            }
          }
          EOL
          
          echo "Routes configuration:"
          cat dist/deploy/routes.json

      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_SEA_08385421E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "frontend/dist/deploy"
          output_location: ""
          skip_app_build: true
          routes_location: "frontend/dist/deploy/routes.json"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_SEA_08385421E }}
          action: "close"
